export enum SocketEvent {
  JOIN_ROOM = 'JOIN_ROOM',
  LEAVE_ROOM = 'LEAVE_ROOM',
  JOIN_ROOM_1 = 'JOIN_ROOM_1',
  JOIN_ROOM_2 = 'JOIN_ROOM_2',

  NEW_MESSAGE = 'NEW_MESSAGE',
  NEW_MESSAGE_ROOM = 'NEW_MESSAGE_ROOM',

  NEW_MESSAGE_ROOM_2 = 'NEW_MESSAGE_ROOM_2',
}
