version: '3'
services:
  mysql:
    image: mysql:8.0.25
    container_name: mysql
    platform: linux/amd64
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql_mode="" --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: p1
      MYSQL_DATABASE: demo
      MYSQL_USER: thanhle
      MYSQL_PASSWORD: p1
      LANG: C.UTF-8
    ports:
      - 3306:3306

  redis:
    image: 'redis:6-alpine'
    container_name: redis
    ports:
      - 6379:6379
